name: Hexo
on: push
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.
        dst_path: hexo/
        dst_owner: zxiaosi
        dst_repo_name: zxiaosi.github.io
        dst_branch: master
        src_branch: gh-pages
        clean: true # 这里要保证目标目录先清空，否则非主页仓库若有删除文件就不会同步到主页仓库
